default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: username
  password: username

development:
  <<: *default
  database: postgresan

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5